name: release

on:
  push:
    tags:
      - "v*"
      - "v*-*"

permissions:
  contents: write

env:
  BUILD_IMAGE: ghcr.io/techknowlogick/xgo:latest
  IMAGE_CACHE_DIR: /mnt/docker-images

jobs:
  cache-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Docker image
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: ${{ env.IMAGE_CACHE_DIR }}
          key: ${{ runner.os }}-docker-${{ env.BUILD_IMAGE }}

      - name: Pull Docker image
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: |
          sudo mkdir -p ${{ env.IMAGE_CACHE_DIR }}
          docker pull ${{ env.BUILD_IMAGE }}
          sudo docker save ${{ env.BUILD_IMAGE }} -o ${{ env.IMAGE_CACHE_DIR }}/xgo.tar
                  

  build-desktop:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: darwin
            arch: amd64
            suffix: _amd64
            display_os: macOS
          - os: darwin
            arch: arm64
            suffix: _arm64
            display_os: macOS
          - os: windows
            arch: amd64
            suffix: .exe
            display_os: Windows
          - os: windows
            arch: 386
            suffix: _i386.exe
            display_os: Windows

    runs-on: ubuntu-latest
    needs: cache-docker
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Docker image cache
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.IMAGE_CACHE_DIR }}/xgo.tar
          key: ${{ runner.os }}-docker-${{ env.BUILD_IMAGE }}
      
      - name: Load Docker image
        continue-on-error: true
        if: steps.restore-cache.outputs.cache-hit == 'true'
        run: |
          echo "Docker image loaded from cache."
          sudo docker load -i ${{ env.IMAGE_CACHE_DIR }}/xgo.tar

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install XGO
        run: |
          go install src.techknowlogick.com/xgo@latest

      - name: Build Binary
        run: |
          xgo --targets=${{ matrix.os }}/${{ matrix.arch }} \
            --out krillinai_desktop \
            --dest build \
            ./cmd/desktop

      - name: Get Version
        id: version
        uses: actions/github-script@v7
        with:
          script: |
            const rawTag = '${{ github.ref_name }}';
            const version = rawTag.replace(/^v/, ''); // Remove the leading 'v' if present
            console.log(`Version: ${version}`);
            core.setOutput('version', version);

      - name: Rename Binary
        id: rename
        run: |
          binary_name="KrillinAI_Desktop_${{ steps.version.outputs.version }}_${{ matrix.display_os }}${{ matrix.suffix }}"
          sudo mv build/krillinai_desktop* build/$binary_name 
          echo "binary_name=$binary_name" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.rename.outputs.binary_name }}
          path: build/${{ steps.rename.outputs.binary_name }}

  goreleaser:
    needs: build-desktop
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: build

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
